name: flutter_callkit_platform_interface
description: "Common platform interface for the flutter_callkit plugin"
version: 0.0.1
homepage: https://github.com/cybex-dev/flutter_callkit

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
